# Generated by Django 4.1.2 on 2022-10-19 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_appointment_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='apt_date',
            field=models.CharField(max_length=50),
        ),
    ]
